// Mocks generated by Mockito 5.1.0 from annotations
// in balance_history/test/helper/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:balance_history/data/failure.dart' as _i5;
import 'package:balance_history/data/services/api/api_service.dart' as _i7;
import 'package:balance_history/domain/entities/history.dart' as _i6;
import 'package:balance_history/domain/repositories/history_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i3.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.History>>> getAllBalanceHistory(
          String? address) =>
      (super.noSuchMethod(Invocation.method(#getAllBalanceHistory, [address]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.History>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.History>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.History>>>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.History>> getAllBalanceHistory(String? address) =>
      (super.noSuchMethod(Invocation.method(#getAllBalanceHistory, [address]),
              returnValue: Future<List<_i6.History>>.value(<_i6.History>[]))
          as _i4.Future<List<_i6.History>>);
}
